### ISSUE TITLE
I have a question about the code in this repository, which I think is an error.

### ISSUE THREAD

**Issue by yryo1005** [ymalitsky/adaptive_GD#1]
Hello, excuse me for asking out of the blue.

I am very interested in your paper and am now thinking about its development.

I have a question about the code in this repository, which I think is an error.

In adaptive_GD/pytorch/optimizers.py, 

Line 39, "grad_dif_norm += (d_p - prev_d_p).norm().item() ** 2"  is not be,  "grad_dif_norm += (d_p - prev_d_p).pow(2).sum().item()"?

and also Line 40, "grad_dif_norm += (p.data - prev_p.data).norm().item() ** 2"  is not be,  "param_dif_norm += (p.data - prev_p.data).pow(2).sum().item()"?

This is because in torch.Tensor.norm(), all the elements of the tensor are squared, added together, and the square root is taken.

In the original code, the Euclidean norm of the difference of each layer parameter (or gradient) is found, the result is squared, the squared Euclidean norm of all layers is added, and the square root of the result is taken.

This is not the same as the formula in the paper, is it?

Lastly, I am sorry if my English is not good enough to convey my intentions well.

I hope you understand that I am not malicious in my questions and that I am asking them out of simple doubt and interest in your research.

**Comment by konstmish** [comment]
Hi, thank you for the question.  
As you correctly wrote, `torch.Tensor.norm()` computes the norm of the difference and then takes the square root. Since we want `group['grad_dif_norm']` to be the norm of the difference of the whole gradient vector, we square it to get the sum of squares and then sum it over all layers. So in fact, `grad_dif_norm` computes the squared norm of the difference of the gradients, and then we compute `group['grad_dif_norm'] = np.sqrt(grad_dif_norm)`, which is the norm. The same happens with `param_dif_norm`. I hope that answers your question, but let me know if not.

Please also let us know if there is anything else we can help with, I'd be happy to explain other details.
